### ISSUE TITLE
 java.lang.VerifyError: com/creageek/segmentedbutton/SegmentedButton

### ISSUE THREAD

**Issue by islamYMansour** [creageek/segmented#5]
i have an issue its appear on  
Android  4.4.2
Galaxy Note2
can anyone help me?
Fatal Exception: java.lang.VerifyError: com/creageek/segmentedbutton/SegmentedButton
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at android.view.LayoutInflater.createView(LayoutInflater.java:600)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)

**Comment by shahkarraza** [comment]
I am having the same error. Can you please share any solution?
